CREATE TABLE escolas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL UNIQUE,
    descricao VARCHAR(255) NOT NULL
);

INSERT INTO escolas (nome, descricao) VALUES
    ('Fundamentos', 'Logica, Git e orientacao a objetos.'),
    ('Backend', 'Algoritmos, APIs e bancos de dados.'),
    ('Frontend', 'Interfaces, HTML, CSS e JavaScript.'),
    ('Seguranca', 'Autenticacao, criptografia e protecao.'),
    ('Dados', 'Estatistica, analise de dados e inteligencia artificial.');