spring.application.name=CodeQuest
server.port=${SERVER_PORT:8081}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/codequest}
spring.datasource.username=${DB_USER:codequest}
spring.datasource.password=${DB_PASSWORD:codequest}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
